#!/bin/sh
echo "PROD : transfertCP.js"
/usr/local/bin/node /home/inside/apps/prod/task/transfertCP.js >> prod.log 
# echo "DEV : transfertCP.js"
# /root/node/node /home/inside/apps/dev/task/transfertCP.js >> dev.log &