#!/bin/sh
echo "PROD : validationConges.js"
/usr/local/bin/node /home/inside/apps/prod/task/validationConges.js >> prod.log
# echo "DEV : validationConges.js"
# /root/node/node /home/inside/apps/dev/task/validationConges.js >> dev.log &